name: mouse-jiggler
options:
  bundleIdPrefix: com.mousejiggler
  deploymentTarget:
    macOS: '13.0'
packages:
  LaunchAtLogin:
    exactVersion: 5.0.0
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern
settings:
  base:
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    PRODUCT_BUNDLE_IDENTIFIER: com.mousejiggler.app
targets:
  mouse-jiggler:
    dependencies:
    - package: LaunchAtLogin
    info:
      path: mouse-jiggler/Info.plist
      properties:
        CFBundleDisplayName: Mouse Jiggler
        LSApplicationCategoryType: public.app-category.utilities
        LSUIElement: true
    platform: macOS
    settings:
      base:
        ENABLE_HARDENED_RUNTIME: true
        ENABLE_USER_SELECTED_FILES: readwrite
        INFOPLIST_FILE: mouse-jiggler/Info.plist
        MACOSX_DEPLOYMENT_TARGET: '13.0'
        SUPPORTS_MACCATALYST: false
        SWIFT_VERSION: '5.0'
    sources:
    - mouse-jiggler
    type: application
